# Generated by Django 5.2.1 on 2025-05-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_category_quiz_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duración del quiz en segundos (opcional)', null=True),
        ),
    ]
