# Generated by Django 5.2.1 on 2025-06-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
